name: test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --console=plain

      - name: Test with Gradle
        run: |
          result=$(./gradlew test --console=plain | grep -oP "(?<=result: )\d+")
          echo "::set-env name=RESULT::$result"

  assert:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: echo "Result is ${{ env.RESULT }}"
